CovidVaccin_Project/CoVaccine/urls.py
from . import views
from django.urls import path
app_name = 'CoVaccine'

urlpatterns = [
    path('',views.Home,name='Home'),
]

CovidVaccin_Project/CovidVaccin_Project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from CovidVaccin_Project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('CoVaccine.urls')),
    path('Register/',include('Registration.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

CovidVaccin_Project/Registration/urls.py
from . import views
from django.urls import path
app_name = 'Registration'

urlpatterns = [
    path('register',views.register,name='Register'),
    path('login',views.Login,name='Login'),
    path('logout',views.logout,name='logout'),
    path('user_details',views.User_Details,name='User_Details'),

    path('add/', views.person_create_view, name='person_add'),
    path('<int:pk>/', views.person_update_view, name='person_change'),

    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),  # AJAX
]

CovidVaccin_Project/CoVaccine/models.py
from django.db import models

# Create your models here.

CovidVaccin_Project/CoVaccine/views.py
from django.shortcuts import render

# Create your views here.
def Home(request):
    return render(request,"index.html")

CovidVaccin_Project/templates/Login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HTML VS CSS</title>
    <STyle>
        * {
            box-sizing: border-box;
            font-family: "Open Sans", sans-serif;
            margin: 0;
            padding: 0;
       }
        .flex-column-centered {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
       }
        .login-div {
            min-height: 100vh;
            background-image: linear-gradient(rgb(0, 89, 255), rgb(255, 255, 255));
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
       }
        .login-div .login-comps {
            background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5));
            padding: 2em;
            color: white;
       }
        .login-div form {
            padding: 20px 0;
            position: relative;
            z-index: 2;
       }
        .login-div form input[type="text"], .login-div form input[type="password"] {
            margin: 0.5rem auto;
            background: rgba(80, 227, 194, 0.2);
            box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
            backdrop-filter: blur(4px);
            -webkit-backdrop-filter: blur(4px);

            border: 1px solid rgba(255, 255, 255, 0.18);
            padding: 0.5em;
            width: 400px;
            outline: none;
       }
        .login-div form input[type="text"]:focus, .login-div form input[type="password"]:focus {
            background-color: rgba(0, 0, 0, 0.329);
            color: white;
       }
        .login-div form input[type="submit"] {
            background: rgb(255, 0, 157);
            color: white;
            border-radius: 5px;
            margin: 0.5rem auto;
            padding: 0.5rem;
            width: 250px;
            border: none;
       }
        .login-div form input[type="submit"]:active {
            transform: scale(0.95);
       }
        .login-div form input[type="text"]::placeholder, .login-div form input[type="password"]::placeholder {
            color: white;
       }
        .login-div .text-center {
            text-align: center;
       }
        .login-div a {
            text-decoration: none;
            color: white;
       }
        @media (max-width: 576px) {
            .login-div {
                padding: 2rem 1.5rem !important;
           }
            .login-div .login-comps, .login-div input[type="text"], .login-div input[type="password"] {
                width: 100% !important;
           }
       }

    </STyle>
</head>
<body>
    <div class="login-div flex-column-centered">
        <div class="login-comps">
          <h1 class="text-center">Login</h1>
          <form action="login" method="post" class="flex-column-centered">
			   {% csrf_token %}

            <input type="text" name="username"  placeholder="Username" >

            <input type="password" name="password" placeholder="Password" >

            <input type="submit" value="Login">

          </form>

          <a href="{% url 'Registration:Register' %} "><p class="text-center">Create a new</p></a>

        </div>
      </div>
</body>
</html>

CovidVaccin_Project/templates/Registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HTML VS CSS</title>
    <STyle>
        * {
            box-sizing: border-box;
            font-family: "Open Sans", sans-serif;
            margin: 0;
            padding: 0;
       }
        .flex-column-centered {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
       }
        .login-div {
            min-height: 100vh;
            background-image: linear-gradient(rgb(0, 89, 255), rgb(255, 255, 255));
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
       }
        .login-div .login-comps {
            background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5));
            padding: 2em;
            color: white;
       }
        .login-div form {
            padding: 20px 0;
            position: relative;
            z-index: 2;
       }
        .login-div form input[type="text"], .login-div form input[type="password"] {
            margin: 0.5rem auto;
            background: rgba(80, 227, 194, 0.2);
            box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
            backdrop-filter: blur(4px);
            -webkit-backdrop-filter: blur(4px);

            border: 1px solid rgba(255, 255, 255, 0.18);
            padding: 0.5em;
            width: 400px;
            outline: none;
       }
        .login-div form input[type="text"]:focus, .login-div form input[type="password"]:focus {
            background-color: rgba(0, 0, 0, 0.329);
            color: white;
       }
        .login-div form input[type="submit"] {
            background: rgb(255, 0, 157);
            color: white;
            border-radius: 5px;
            margin: 0.5rem auto;
            padding: 0.5rem;
            width: 250px;
            border: none;
       }
        .login-div form input[type="submit"]:active {
            transform: scale(0.95);
       }
        .login-div form input[type="text"]::placeholder, .login-div form input[type="password"]::placeholder {
            color: white;
       }
        .login-div .text-center {
            text-align: center;
       }
        .login-div a {
            text-decoration: none;
            color: white;
       }
        @media (max-width: 576px) {
            .login-div {
                padding: 2rem 1.5rem !important;
           }
            .login-div .login-comps, .login-div input[type="text"], .login-div input[type="password"] {
                width: 100% !important;
           }
       }

    </STyle>
</head>
<body>
    <div class="login-div flex-column-centered">
        <div class="login-comps">
          <h1 class="text-center">Registration Form</h1>
          <form action="register" method="post" class="flex-column-centered">
			   {% csrf_token %}
            <input type="text" name="username"  placeholder="Username" required>

              <input type="text" name="email" id="mail" placeholder="Email" required>

            <input type="password" name="password" id="password" placeholder="Password" required>

            <input type="password" name="cpassword" id="cpassword" placeholder="confirm password" required>

            <input type="submit" value="Register">

          </form>
            {% for msg in messages %}
            {{msg}}
            {% endfor %}
        </div>
      </div>
</body>
</html>

CovidVaccin_Project/templates/User_Details.html
<div class="container">
    <div class="text-center">
        Welcome
        {% for form in form %}
            {{form.First_Name}}
        {% endfor %}
    </div>
</div>

CovidVaccin_Project/templates/persons/city_dropdown_list_options.html
<option value="">Select Your Center</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

CovidVaccin_Project/templates/persons/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Vaccine Registration</title>

    <STyle>
        * {
            box-sizing: border-box;
            font-family: "Open Sans", sans-serif;
            margin: 0;
            padding: 0;
       }
        .flex-column-centered {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
       }
        .login-div {
            min-height: 100vh;
            background-image: linear-gradient(rgb(0, 89, 255), rgb(255, 255, 255));
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
       }
        .login-div .login-comps {
            background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5));
            padding: 2em;
            color: white;
       }
        .login-div form {
            padding: 20px 0;
            position: relative;
            z-index: 2;
       }
        .login-div form input[type="text"], .login-div form input[type="password"] {
            margin: 0.5rem auto;
            background: rgba(80, 227, 194, 0.2);
            box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
            backdrop-filter: blur(4px);
            -webkit-backdrop-filter: blur(4px);

            border: 1px solid rgba(255, 255, 255, 0.18);
            padding: 0.5em;
            width: 400px;
            outline: none;
       }
        .login-div form input[type="text"]:focus, .login-div form input[type="password"]:focus {
            background-color: rgba(0, 0, 0, 0.329);
            color: white;
       }
        .login-div form input[type="submit"] {
            background: rgb(255, 0, 157);
            color: white;
            border-radius: 5px;
            margin: 0.5rem auto;
            padding: 0.5rem;
            width: 250px;
            border: none;
       }
        .login-div form input[type="submit"]:active {
            transform: scale(0.95);
       }
        .login-div form input[type="text"]::placeholder, .login-div form input[type="password"]::placeholder {
            color: white;
       }
        .login-div .text-center {
            text-align: center;
       }
        .login-div a {
            text-decoration: none;
            color: white;
       }
        @media (max-width: 576px) {
            .login-div {
                padding: 2rem 1.5rem !important;
           }
            .login-div .login-comps, .login-div input[type="text"], .login-div input[type="password"] {
                width: 100% !important;
           }
       }

    </STyle>
</head>
<body>
 <div class="login-div flex-column-centered">
        <div class="login-comps">
          <h1 class="text-center">Registration Form</h1>

<form action="http://127.0.0.1:8000/Register/add/" method="post" id="personForm" data-cities-url="{% url 'Registration:ajax_load_cities' %}" class="flex-column-left">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_district").change(function () {
        const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const districtId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'district_id': districtId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                console.log(data);
                $("#id_vaccine_center").html(data);  // replace the contents of the city input with the data that came from the server

                /*

                let html_data = '<option value="">Select Your Center</option>';
                data.forEach(function (vaccine_center) {
                    html_data += `<option value="${.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_vaccine_center").html(html_data);

                */
            }
        });

    });
</script>
</div>
 </div>
</body>
</html>